### ISSUE TITLE
Firefox reports these extensions aren't compatible with FF57.0b12

### ISSUE THREAD

**Issue by skorasaurus** [andywillis/uws-metafilter-favouriteers#1]
Hi, 

Thanks for making these! I was about to install them for myself but  
when I visit https://addons.mozilla.org/en-US/firefox/collections/andyuws/metafilter/
they are reported as not compatible - see screenshot 
![selection_014](https://user-images.githubusercontent.com/955351/32190977-e354bedc-bd85-11e7-8d05-c1e82de63fbc.png)

I am running 57.0b12 (64-bit) on ubuntu.

**Comment by andywillis** [comment]
Ah. Yeah, you have to decide what platform it works on when you submit the extension, and since I only have/develop on Windows, that was all I selected. I've updated the platform, so give it another go.

**Comment by skorasaurus** [comment]
Thanks for the prompt response! 

Sorry, I checked https://addons.mozilla.org/en-US/firefox/collections/andyuws/metafilter/ again and it stills unavailable :(

**Comment by andywillis** [comment]
I've uploaded new versions as "All platform". See if that works.

**Comment by skorasaurus** [comment]
Hi, 

That most recent update works for me! Thanks again for fixing and making these!

**Comment by andywillis** [comment]
Note the favouriteers extension needs a bit of work as it's a bit flaky, but the other two work really well.
